---
title: "Mapping oak-wilt using Sentinel-2"
date: "`r Sys.Date()`"
output: md_document
author: "J. Antonio Guzmán Q."
---

This site serves as a documentation for the project of Mapping oak-wilt using
Sentinel-2. 

All the data is currently storage at the tier-1 of [Minnesota Supercomputing Institute](https://www.msi.umn.edu/) under `gruops/cavender/shared/oak-wilt`.

Many steps of workflow that leads to the structure of the project and data used 
comes from [FORCE](https://force-eo.readthedocs.io/en/latest/). Thus, try to be 
familiar with it before to reproduce any of the steps.

## Folder structrue

Under `gruops/cavender/shared/oak-wilt` the folders follow the structure:

```
/oak-wilt
  - /level1
  - /level2
  - /level3_monthly-mean
  - /level3
  - /level4
  - /log
    -- /log_sentinel
    -- /log_landsat
  - /param
  - /msi_jobs
  - /misc
    -- /csd
    -- /dem
    -- /GIS
    -- /grid
    -- /mask
    -- /wvdb
   - /temp
```

* `/level1`: contains all the Landsat-8 and Sentinel-2 imagery downloaded.
* `/level2`: contains all the ARD imagery processed through [force-level2](https://force-eo.readthedocs.io/en/latest/howto/l2-ard.html#tut-ard)
* `/level3_monthly-mean`: contains the 5-years average monthly observations of 
Landsat-8 for the co-registration of Sentinel-2.
* `/level3`: contains all the ARD imagery level3 (e.g., cloud, illumination, shadow masked).
* `/level4`: ---
* `/log`: records of the scene processing to create level2 from each sensor.
* `/param`: contains all the `.prm` files to run FORCE for this project.
* `/msi_jobs`: contains all the scripts submitted to MSI for processing.
* `/misc/csd`: contains the list of scenes to be accessed through Google Cloud Storage.
Keep it updated if not scenes available using something similar like `force-level1-csd -u ~/misc/csd` following [force-level1-csd](https://force-eo.readthedocs.io/en/latest/howto/level1-csd.html#tut-l1csd) module.
* `/misc/dem`: contains the Digital Elevation Model that cover the extend of 
both Landsat-8 and Sentinel-2 imagery. 
* `/misc/GIS`: miscellaneous GIS files for the tiles, states, and areas of interest.
* `/misc/mask`: contains the mask of area of interest for both states.
* `/misc/grid`: GIS files with the datacube tile description.
* `/misc/wvdb`: contains the water vapor database.
* `/temp`: auxiliary folder for temporal data. Data that falls there can be removed
at any time.

## Sources of Data

#### Digital Elevation Model

Copernicus GLO-30 Digital Elevation Model for both states is used, and can be 
downloaded from [OpenTography](https://portal.opentopography.org/raster?opentopoID=OTSDEM.032021.4326.3) if required.

#### Water Vapor Database

This databases was accessed from [Zenodo](https://zenodo.org/record/4468701#.YfF4IPvF05k).
If required, it can be updated following FORCE [guide](https://force-eo.readthedocs.io/en/latest/howto/wvdb.html).

#### Landsat-8

Landsat-8 scenes were downloaded from Google Cloud Storage using [force-level1-csd](https://force-eo.readthedocs.io/en/latest/howto/level1-csd.html).
The following tiles were used:

```
026031 025031 024031 023031 022031 030030 029030 028030 027030 026030 025030 
024030 023030 022030 021030 030029 029029 028029 027029 026029 025029 024029 
023029 022029 021029 031028 030028 029028 028028 027028 026028 025028 024028 
023028 022028 031027 030027 029027 028027 027027 026027 025027 024027 023027 
031026 030026 029026 028026 027026 026026 025026 024026 031025 030025 029025 
028025 027025
```

#### Sentinel-2

Sentinel-2 (S2A and S2B) were also downloaded from from Google Cloud Storage using [force-level1-csd](https://force-eo.readthedocs.io/en/latest/howto/level1-csd.html).
The following tiles were used:

```
T14TPP T14TPQ T14TPR T14TPS T14TPT T14TQP T14TQQ T14TQR T14TQS T14TQT T14UPU 
T14UPV T14UQU T14UQV T15TUJ T15TUK T15TUL T15TUM T15TUN T15TVJ T15TVK T15TVL 
T15TVM T15TVN T15TWJ T15TWK T15TWL T15TWM T15TWN T15TXH T15TXJ T15TXK T15TXL 
T15TXM T15TXN T15TYH T15TYJ T15TYK T15TYL T15TYM T15UUP T15UUQ T15UVP T15UWP 
T15UXP T15UYP T16TCN T16TCP T16TCQ T16TCR T16TCS T16TDN T16TDP T16TDQ T16TDR 
T16TER
```

## Working at Minnesota Supercomputing Institute


