site_name: Cavender-Bares lab
theme:
    logo: 'fab1.png'
    features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - search.share
    - header.autohide
    name: material
    palette: 
    - scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    icon:
      repo: fontawesome/brands/gitlab
plugins:
    - search
    - git-revision-date-localized:
    - table-reader
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde
  - pymdownx.caret
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
repo_url: https://https://github.com/Cavender-Bares-Lab/Data-management-lab
repo_name: Cavender-Bares-Lab/Data-management-lab
extra_css:
  - css/extra.css
nav:
  - Home: 'index.md'
  - User guide: 'user-guide/user_guide.md'
  - Lab Information: 
    - Welcome package: 'welcome_package.md'
    - Leaving package: 'leaving_package.md'
    - Important Lab Information: 'lab_information/information-of-interest.md'
    - Sampling and Analytical Costs: 'lab_information/costs.md'
    - Software: 'lab_information/software.md'
    - Methods Publications: ''
    - Permits: 'lab_information\Permits\Permits.md'
  - Project Information:
    - Introduction: 'project_information\introduction.md'
    - BII ASCEND: 'project_information\bii_ascend\biiascend.md'
    - Dimensions of Biodiversity:
      - Oaks US - China: 'project_information\dimensions\Oaks US China\Oaks-US-China.md'
      - NASA: 'project_information\dimensions\NASA\NASA.md'
    - Global Oaks:
      - American Oak Project: 'project_information\Global oaks\american_oaks\american_oaks.md'
      - Live Oaks: 
        - LOARD: 'project_information\live_oaks\loard.md'
    - LTER:
      - Forest and Biodiversity: 'project_information\lter\FAB\FAB.md'
      - GLADES: 'project_information\lter\glades.md'
      - Willow: ''
    - Macrosystems: ''
    - NPS Aspen: ''
    - Oak Wilt: 'project_information\oak_wilt\oak-wilt.md'
  - Protocols:
    - Introduction: 'protocols/introduction_protocols.md'
    - Acid Bath Preparation and Neutralization: 'protocols/acid_baths_preparation_and_neutralization.md'
    - Acorn Collection and Processing:
      - Acorn Collection Protocol: 'protocols/acorn_collection_protocol.md'
      - Acorn Processing: 'protocols/acorn_processing.md'
    - Ankom Fiber Analyzer: 'protocols/ankom_fiber_analyzer.md'
    - Balance Interface Program Instructions for Hydraulic Conductivity: 'protocols/balance_interface_program_interface_hydraulic_conductivity.md'
    - FAB surveys:
      - Growth Measurements: 'protocols/growth_measurements.md'
      - Herbivory Survey: ''
      - Reproduction Survey: 'protocols/reproduction_survey.md'
    - Hansatech Fluorometer:
      - (Pre-dawn) Dark/Light Adapted Leaf Measurements: 'protocols/predawn_hansatech_fluorometer.md'
      - (Alternative) Dark/Light Adapted Leaf Measurements: 'protocols/hansatech_fluorometer_dark_adapted_leaf_measurements.md'
      - Interface Settings: 'protocols/interface_settings.md'
    - HPLC:
      - HPLC - Summary: 'protocols/hplc_summary.md'
      - HPLC - Pigment Calibration: 'protocols/pigment_calibration.md'
      - HPLC - Pigment Extraction: 'protocols/pigment_extraction.md'
      - HPLC - Run Samples: 'protocols/hplc_run_samples.md'
      - HPLC - ImageJ: 'protocols/hplc_imagej.md'
      - HPLC - Export Data: 'protocols/hplc_export_data.md'
    - Leaf Surface Sterilization: 'protocols/surface_sterilization.md'
    - Licor 6400 Warmup Protocol: 'protocols/licor_6400_warmup_protocol.md'
    - Measuring leaf area: 'protocols/measuring_leaf_area.md'
    - Muffle Furnace Use: 'protocols/muffle_furnace_use.md'
    - Pneumatic Protocol: 'protocols/pneumatic_protocol.md'
    - Radial Diffusion Assay for Tannins: 'protocols/tannins.md'
    - Soil:
      - Dissolved Organic Carbon and Total Nitrogen: 'protocols/dissolved_organic_carbon_and_total_nitrogen.md'
      - Inorganic Nitrogen Assays for N-min: 'protocols/inorganic_nitrogen_assays_in_microplates_for_netmin.md'
      - Soil and Leaf Litter CN Protocol: 'protocols/soil_and_leaf_litter_cn_protocol_on_elemental_analyzer.md'
      - Soil and Plant Phosphorus Protocol: 'protocols/soil_and_plant_phosphorus_protocol.md'
      - Soil pH Hybrid Protocol: 'protocols/soil_ph_hybrid_protocol.md'
      - Soil KCl Extracts pH Protocol: 'protocols/pH_soil_extracts.md'
      - Soil sampling and Processing:
        - FAB:
          - N-min Summary and Sampling Notes: 'protocols/nmin_summary_and_sampling_notes.md'
          - N-min Preparation: 'protocols/nmin_preparation.md'
          - N-min Coring: 'protocols/nmin_coring.md'
          - N-min Processing Day 1: 'protocols/nmin_processing_day1.md'
          - N-min Processing Day 2: 'protocols/nmin_processing_day2.md'
    - Spectrometers:
      - PSR:
        - PSR Leaf Measurements: 'protocols/spectral_evolution_psr+.md'
      - SVC:  
        - SVC Bluetooth Connection: 'protocols/svc_bluetooth_connection.md'
        - SVC Leaf Measurements: 'protocols/svc_leaf_measurements.md'
      - Care and Cleaning of Spectralon: 'protocols/care_and_cleaning_of_spectralon.md'
    - Thermal Camera:
      - Thermal Camera - Set Up and Connection: 'protocols/thermal_camera_set_up.md'
      - ResearchIR - License Transfer: 'protocols/researchir_license.md'
    - VLA:
      - VLA Methods: 'protocols/vla_methods.md'
      - VLA ImageJ Methods: 'protocols/vla_imagej_methods.md'
  - Data management:
    - Introduction: 'data-management\introduction-data.md'
    - Dimensions:
      - Oaks US - China: 'data-management\oaks.md'
      - NASA: 'data-management\nasa.md'
    - Live-Oaks:
      - Phylogeography: 'data-management\Live Oaks\Phylogeography\phylogeography-_data.md'
      - LOARD: 'data-management\Live Oaks\LOARD\LOARD.md'
    - LTER:
      - FAB 1: 'data-management\FAB\fab1.md'
      - FAB 2: 'data-management\FAB\fab2.md'
    - Macrosystems: ''
    - Oak Wilt:
      - Grand Challenges: ''
      - MITPPC: ''  
      - NASA-ROSES:
        - Mapping oak-wilt using Sentinel 2: 'data-management/nasa-roses/mapping-sentienl2/oak-wilt.md'      
      - US Forest Service: ''
  - Lab Products:
    - JCB Compilation: 'lab_products\jcb.md'
    - BII ASCEND: 'lab_products\bii_ascend_products.md'
    - Dimensions of Biodiversity:
      - Oaks US - China: ''
      - NASA: 'lab_products\dob_nasa.md'
    - Live Oaks:
      - LOARD: 'lab_products\loard.md'
      - Phylogeography: 'lab_products\live_oaks_phylogeography_products.md'
    - LTER:
      - Forest and Biodiversity: 'lab_products\fab_products.md'
      - GLADES: ''
      - Willow: ''
    - NPS Aspen: 'lab_products/nps_aspen.md'
    - Oak Wilt:
      - MITPPC: 'lab_products/mitppc_oakwilt_products.md'
  - About:
    - License: ''
    - Release Notes: ''