site_name: Cavender-Bares lab
theme:
    name: material
    palette: teal
nav:
  - Home: 'index.md'
  - User guide: 'user-guide/user_guide.md'
  - Welcome package: ''
  - Protocols:
    - 'Surface Sterilization': 'protocols/surface_sterilization.md'
    - 'Hazardous Waste Handling': 'protocols/hazardous_waste_handling.md'
    - 'Measuring leaf area': 'protocols/measuring_leaf_area.md'
    - 'Ankom Fiber Analyzer': 'protocols/ankom_fiber_analyzer.md'
  - 'Data management': ''
  - About:
    - 'License': ''
    - 'Release Notes': ''