site_name: Cavender-Bares lab
theme:
    logo: 'fab1.png'
    features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - search.share
    - header.autohide
    name: material
    palette: 
      primary: teal
      accent: indigo
plugins:
    - search
    - table-reader
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - css/extra.css
nav:
  - Home: 'index.md'
  - User guide: 'user-guide/user_guide.md'
  - Lab Information: 
    - Welcome package: 'welcome_package.md'
    - Leaving package: ''
    - Important Lab Information: 'information-of-interest/information-of-interest.md'
    - Sampling and Analytical Costs: 
      - Leaves:
        - Carbon and Nitrogen: ''        
        - Fiber: ''
        - Pigment (HPLC): ''
        - Leaf Veination: ''
        - Osmometer: ''
        - Phosphorus: ''
      - Soil sampling:
        - Carbon and Nitrogen: ''
        - LTER FAB Specific:
          - LTER Soil Sampling and Analysis Costs: ''
        - Nitrogen Mineralization: ''
        - Microbial Biomass: ''
        - Phosphorus: ''
        - Soil Respiration: ''
    - Methods Publications: ''
    - Permits: 'information-of-interest\Permits\Permits.md'
  - Project Information:
    - BII ASCEND: 'project_information\bii_ascend\biiascend.md'
    - Dimensions of Biodiversity:
      - Oaks US - China: 'project_information\dimensions\Oaks US China\Oaks-US-China.md'
      - NASA: 'project_information\dimensions\NASA\NASA.md'
    - Global Oaks:
      - American Oak Project: 'project_information\Global oaks\american_oaks\american_oaks.md'
      - Live Oaks: 
        - LOARD: 'project_information\live_oaks\loard.md'
    - LTER:
      - Forest and Biodiversity: 'project_information\lter\FAB\FAB.md'
      - GLADES: 'project_information\lter\glades.md'
      - Willow: ''
    - NPS Aspen: ''
    - Oak Wilt: 'project_information\oak_wilt\oak-wilt.md'
  - Protocols:
    - Acid Bath Preparation and Neutralization: 'protocols/acid_baths_preparation_and_neutralization.md'
    - Acorn Collection and Processing:
      - Acorn Collection Protocol: 'protocols/acorn_collection_protocol.md'
      - Acorn Processing: 'protocols/acorn_processing.md'
    - Ankom Fiber Analyzer: 'protocols/ankom_fiber_analyzer.md'
    - Balance Interface Program Instructions for Hydraulic Conductivity: 'protocols/balance_interface_program_interface_hydraulic_conductivity.md'
    - Care and Cleaning of Spectralon: 'protocols/care_and_cleaning_of_spectralon.md'
    - FAB surveys:
      - Growth Measurements: 'protocols/growth_measurements.md'
      - Herbivory Survey: ''
      - Reproduction Survey: 'protocols/reproduction_survey.md'
    - Hansatech Fluorometer:
      - (Pre-dawn) Dark/Light Adapted Leaf Measurements: 'protocols/predawn_hansatech_fluorometer.md'
      - (Alternative) Dark/Light Adapted Leaf Measurements: 'protocols/hansatech_fluorometer_dark_adapted_leaf_measurements.md'
      - Interface Settings: 'protocols/interface_settings.md'
    - HPLC:
      - HPLC ImageJ: 'protocols/hplc_imagej.md'
      - Pigment Extraction: 'protocols/pigment_extraction.md'
      - Pigment Calibration: 'pigment_calibration.md'
      - Run Samples: ''
    - Licor 6400 Warmup Protocol: 'protocols/licor_6400_warmup_protocol.md'
    - Measuring leaf area: 'protocols/measuring_leaf_area.md'
    - Muffle Furnace Use: 'protocols/muffle_furnace_use.md'
    - Pneumatic Protocol: 'protocols/pneumatic_protocol.md'
    - PSR:
      - PSR Leaf Measurements: ''
    - Radial Diffusion Assay for Tannins: 'protocols/tannins.md'
    - Soil:
      - Dissolved Organic Carbon and Total Nitrogen: 'protocols/dissolved_organic_carbon_and_total_nitrogen.md'
      - Inorganic Nitrogen Assays for N-min: 'protocols/inorganic_nitrogen_assays_in_microplates_for_netmin.md'
      - Soil and Leaf Litter CN Protocol: 'protocols/soil_and_leaf_litter_cn_protocol_on_elemental_analyzer.md'
      - Soil and Plant Phosphorus Protocol: 'protocols/soil_and_plant_phosphorus_protocol.md'
      - Soil pH Hybrid Protocol: 'protocols/soil_ph_hybrid_protocol.md'
      - Soil sampling and Processing:
        - FAB:
          - N-min Summary and Sampling Notes: 'protocols/nmin_summary_and_sampling_notes.md'
          - N-min Coring: 'protocols/nmin_coring.md'
          - N-min Preparation: 'protocols/nmin_preparation.md'
          - N-min Processing Day 1: 'protocols/nmin_processing_day1.md'
          - N-min Processing Day 2: 'protocols/nminI_processing_day2.md'
    - Surface Sterilization: 'protocols/surface_sterilization.md'
    - SVC:  
      - SVC Bluetooth Connection: 'protocols/svc_bluetooth_connection.md'
      - SVC Leaf Measurements: 'protocols/svc_leaf_measurements.md'
    - VLA:
      - VLA Methods: 'protocols/vla_methods.md'
      - VLA ImageJ Methods: 'protocols/vla_imagej_methods.md'
  - Data management:
    - Introduction: 'data-management\introduction-data.md'
    - Dimensions:
      - Oaks US - China: 'data-management\oaks.md'
      - NASA: 'data-management\nasa.md'
    - Live-Oaks:
      - Phylogeography: 'data-management\Live Oaks\Phylogeography\phylogeography-_data.md'
      - LOARD: 'data-management\Live Oaks\LOARD\LOARD.md'
    - LTER:
      - FAB 1: 'data-management\FAB\fab1.md'
      - FAB 2: 'data-management\FAB\fab2.md'
    - NASA-ROSES:
      - Mapping oak-wilt using Sentinel 2: 'data-management/nasa-roses/mapping-sentienl2/oak-wilt.md'      
  - Lab Products:
    - JCB Compilation: 'lab_products\jcb.md'
    - BII ASCEND: 'lab_products\bii_ascend_products.md'
    - Dimensions of Biodiversity:
      - Oaks US - China: ''
      - NASA: ''
    - Live Oaks:
      - LOARD: 'lab_products\loard.md'
      - Phylogeography: 'lab_products\live_oaks_phylogeography_products.md'
    - LTER:
      - Forest and Biodiversity: 'lab_products\fab_products.md'
      - GLADES: ''
      - Willow: ''
    - NPS Aspen: 'lab_products/nps_aspen.md'
    - Oak Wilt:
      - MITPPC: 'lab_products/mitppc_oakwilt_products.md'
  - About:
    - License: ''
    - Release Notes: ''