---
title: "Radial Diffusion Assay for Tannins"
date: "`r Sys.Date()`"
output: md_document
author: "Rieske-Kinney Lab"
---

###### Author: Rieske-Kinney; Updated: February 2000

### Goal

Methods documenting radial diffusion assay for tannins.

### Equipment/Supplies

* Acetic acid, glacial 99.9+%
* Acetone
* Agarose, type I
* Ascorbic acid	
* Boiling plate
* Bovine serum albumin (BSA)
* Cork borer
* Light table (optional)
* Oven/growth chamber (30C)
* Parafilm
* Petri dishes
* pH meter or paper		
* Pipettes, glass, 10 ml
* Potassium hydroxide flakes
* 4% KOH solution = 4 g KOH + 100 ml dH2O 
* Ruler or calipers
* Stir plate
* Syringe, Hamilton, 10 ul
* Tannic acid
* Test tubes (13 x 100 mm)
* Thermometer

### I. Reagent Preparation
```
1. Tannic acid solution
    a. 0.5 g tannic acid dissolved in 10 ml of 45% acetone.

2. Buffer (50 mM acetic acid)
    a. 2.87 ml acetic acid
        i.    Measure 2.87 ml acetic acid with glass pipette, add to 900 ml of dH2O.
	      ii.   Adjust to pH 5.0 with KOH solution, then bring volume up to 1000 ml with dH2O. 
	      iii.  Foil, parafilm, and store in refrigerator.

3. 45% acetone with 10 mM ascorbic acid
    a. 450 ml acetone
	  b. 550 ml dH2O
	  c. 1.761 g ascorbic acid
        i.    Measure appropriate volume of acetone and dH2O.  Place in 1000 ml flask.  Add ascorbic acid and mix well with stir bar.  Cap with foil and parafilm.
```

### II. Preparation of Agar Plates
```
1. Set water bath temperature to 40C.  

2. Weigh out 1.0 g of agarose into a 250 ml beaker, and 100 mg of BSA into a 20 ml scintillation vial.1

3. Add 97 ml of acetic acid buffer to the 1.0 g of agarose.

4. Bring 97 ml of buffer/agar to full boil on hot plate.

5. Insert thermometer into buffer/agar and cool to 45C in a 40C water bath.

6. Mix 100 mg BSA into 2 ml buffer using second stir plate.  Stir gently, avoid foaming.

7. When agar temperature reaches 45C, add BSA solution to agar and mix for ~10 sec on a cool plate.3  Rinse BSA vial with 1 ml of buffer and add the ml to the agar to bring total volume to 100 ml.	
 
8. Using a glass pipette, dispense 9.5 ml agar into 100 mm petri dishes.  Dispense quickly, spiraling from the outside towards the middle.  After the 9.5 ml of agar is dispensed, swirl the dishes gently and place on flat surface.

9. If bubbles form in the agar, remove them with a pasteur pipette.

10. After agar cools to room temperature, cover and place upside down.  Store in plastic bag in refrigerator until ready to analyze unknowns.		

11. Use a cork borer to punch 4 wells in agar just prior to dispensing plant extracts. 
```

### III. Tissue Extraction and Sample Preparation
```
1. Tissue should be freeze dried, ground, and stored on dessicant at -15C.

2. Weigh 100 mg plant tissue and place in 13 x 100 disposable test tube.

3. Add 1 ml 45% acetone/ascorbic acid solution.

4. Cork and parafilm.

5. Hold 1 h and 35 min at room temp.  

6. Centrifuge for 30 min.
```
				
### IV. Tannin Assay Procedure
```
1. Punch 4 mm wells into the bottom of agar slabs.  Space 2 cm apart. [Label bottom of petri dish with wax pencil before beginning procedure]

2. Pipette 16 ul of plant extract into each well.  Do two 8 ul aliquots of plant extract and standards into 4 mm wells using a 10 ul micropipette or Hamilton syringe.  Agar must have time to absorb first aliquot of material before adding 2nd aliquot.  The 1 mg and 0.75 standards should be placed alone in separate petri dishes to avoid overlapping of reaction rings.

3. After all sol’tns have been absorbed, seal petri dishes with parafilm and incubate at 30C for 96 h in total darkness.  Do not move plates once incubation has begun.  	

4. Measure precipitate rings after 96 h.
```

### V. Standards
```						
1. Prepare 10 ml of a 50 mg/ml tannic acid solution

	500 mg tannic acid
	10 ml acetone/ascorbic acid solution

	Stir on stir plate.

2. From this solution prepare the following standards.
```
Conc. Standard (mg/ml)    | Vol. of Tannic Acid | Vol. of 45% acetone
--------------------------|---------------------|--------------------
          5			          |       100			      |       900
		      10			        |       200			      |       800
		      20			        |       400			      |       600
		      30			        |       600       		|       400
		      40			        |       800			      |       200
		      50			        |       1000			    |       000
```
3. Dispense 16 ul of each standard into its correct well.  Run duplicates.

4. Cover, parafilm and incubate plates in 30C oven for 96 h.

5. After 96 h measure precipitate rings.
```
	
### VI. Determination of area of reaction rings
```
1. Place petri dish on light table.  Measure diameter of rings in two places (perpendicularly) using a ruler or caliper.  Square the average diameter and record data as diameter squared.

2. Calculate the amount of plant tissue in volume of extract dried down.

3. Calculate the amount of plant tissue in 16 ul aliquot used for assay.

4. Express results as diameter2/ mg plant tissue.

[Plot calibration curve.  Ring diameter on x-axis, [tannic acid] on y-axis.]
```
								
### Notes
```
1. Weigh out agar and BSA ahead of time.

2. Make agarose in 100 ml batches only.  Larger amounts will begin to harden before it is properly dispensed in petri dishes.

3. Do not add BSA too soon or it will denature from high temperature.
```

Equipment, materials and supplies:
acetic acid, glacial 99.9+%		Sigma A-6283	500 ml	$16.15
acetone				Sigma A-4206	1 liter		$16.60
agarose, type I			Sigma A-6013	25 g		$38.50
ascorbic acid				Sigma A-1417	100 g		$20.50
boiling plate
bovine serum albumin (BSA)	Sigma P 7656		5 vials		$19.25
cork borer
light table (optional)
oven/growth chamber (30C)
parafilm
petri dishes
pH meter or paper		
pipettes, glass, 10 ml
Potassium hydroxide flakes.		Aldrich 48,401-6
	4% KOH solution = 4 g KOH + 100 ml dH2O 
ruler or calipers
stir plate
syringe, Hamilton, 10 ul
tannic acid 				Sigma T-0125		250 mg	$16.65
test tubes (13 x 100 mm)
thermometer