---
title: "BII - ASCEND Lab Products"
date: "`r Sys.Date()`"
output: md_document
author: "Cathleen Lapadat"
---

### Conferences/Presentations  
Cavender-Bares J. Spectral biology as a means to understand biodiversity change across scales, American Association for the Advancement of Science, February 2021.  

Cavender-Bares J. The hierarchical organization of life: implications for using spectral properties of plants to detect diversity, ecosystem function and response to global change, Ecological Society of America, August 2020.  

Cavender-Bares J. Harnessing spectral biology to integrate biodiversity from the tree of life to ecosystems, Invited talk, Virtual Workshop on Community Ecology IIWCE, UNIL, Brazil, September 2020.  

Cavender-Bares J, Meireles JE, Williams L, Springer N, Schuman M, Sapes G, Reich PB, Townsend PA. Evolutionary and environmental sources of spectral variation within species, communities and across the plant tree of life to enhance biodiversity detection, American Geophysical Union, December 2020.  

Cavender-Bares J. Evolutionary legacies on ecosystem function and implications for global change: new insights from spectral biology, University of Cambridge, UK, September 2020.  

Cavender-Bares J. Linking plant spectra to functional, genetic and phylogenetic diversity in natural and experimental systems, University of Minnesota Plant Breeding Seminar Series, November 2020.  

Duran, SM. Scaling traits to ecosystem properties: an integrative perspective to understand the consequences of changing biodiversity. University of Puerto Rico, Río Piedras, May 2021.  

Duran SM, Falco N, Wainwright H, Marconi S, Henderson AN, Steltzer H, Brodie E, Saleska SR, Enquist BJ. Using imaging spectroscopy to predict above- and below-ground carbon fluxes: a case study in alpine meadows.  

Kothari S, Beauchamp-Rioux R, Laliberté E, Cavender-Bares J. Reflectance spectroscopy allows rapid, accurate, and non-destructive estimates of functional traits from pressed leaves, Botanical Society of America.  


Pinto-Ledezma JN. Plant community structure and detection. Institute of Biology, Leipzig University, Germany, June 2021.  

Pinto-Ledezma JN. Plant diversity: community structure, composition, and detection. University of Minnesota Ecology, Evolution and Behavior Seminar Series, January 2021.  

Pinto-Ledezma JN. Macroecology and macroevolution in the Neotropics. Department of Geography, Federal University of Rio Grande do Norte, Brazil, October 2020.  

### Publications

[Cavender-Bares, J. M., A. K. Schweiger, J. A. Gamon, H. Gholizadeh, K. Helzer, C. Lapadat, M. D. Madritch, P. A. Townsend, Z. Wang, and S. E. Hobbie. 2021. Remotely detected plant function predicts belowground processes in two midwestern prairie grassland experiments. Ecological Monographs.](https://drive.google.com/file/d/1DW-qOfKmyb0_joAXMiOsB2_mSCniYQzD/view?usp=sharing)  

[Cavender-Bares J., Reich P.B., Townsend P.A., Banerjee A., Butler E., Desai A., Gevens A., Hobbie S.E., Isbell F., Laliberté E., Meireles J.E., Menninger H., Pavlick R.P., Pinto-Ledezma J., Potter C., Schuman M.C., Springer N., Stefanski A., Trivedi P., Trowbridge A., Williams L., Willis C.G., and Yang Y. (2021) BII-Implementation: The causes and consequences of plant biodiversity across scales in a rapidly changing world. Research Ideas and Outcomes 7: e63850](https://drive.google.com/file/d/1yN_vTELn9VL_oqnL88sYvCpNsg187MX5/view?usp=sharing)  

[Kothari S., Beauchamp-Rioux R., Laliberté E., and Cavender-Bares J. Reflectance spectroscopy allows rapid, accurate, and non-destructive estimates of functional traits from pressed leaves, BioRxv](https://drive.google.com/file/d/1LMNr1qep57wswj7q-Wtsxi3DzAovcHwV/view?usp=sharing)  

[Mierles, J.E., Cavender-Bares J., Townsend P.A., Ustin S., Gamon J.A., Schweiger A.K., Schaepman M.E., Asner G.P., Marin R.E., Singh A., Schrodt F., Chlus A., and O'Meara B.C. "Leaf reflectance spectra capture the evolutionary history of seed plants." New Phytologist (2020) 228: 485-493.](https://drive.google.com/file/d/1LenOzmAcmaYjAXsFfDvhxn30E2Ctf9lv/view?usp=sharing)  

[Pellegrini, A.F.A., Hein A., Cavender-Bares J., Montgomery R.A., Staver C.A., Silla F., Hobbie S.E., and Reich P.B. 2021. Disease and fire interact to influence transitions between ecosystem states over a 54-year experiment. Ecology Letters 24: 1007-1017.](https://drive.google.com/file/d/1zt2TIgt2LgbtvbB-KKKJ7jwk8tppMGI9/view?usp=sharing)  

[Pinto-Ledezma J.N. and Cavender-Bares J. 2021.Predicting species distributions and community composition using satellite remote sensing predictors. Scientific Reports 11: 16448.](https://drive.google.com/file/d/1uLwRU0Vs28mNGVnQK7Zf3H7E82tAytS_/view?usp=sharing)  

[Schweiger A.K., Cavender-Bares J., Kothari K., Madritch M., Grossman J., Townsend P., Gholizadeh H., Wang R., and Gamon J. 2021. Coupling spectral and resource-use complementarity in experimental grassland and forest communities. Proceedings of the Royal Society B.](https://drive.google.com/file/d/19_TggiyG3GhGOYkfauWW-KxSfESVLNBm/view?usp=sharing)  

[Williams L.J., Cavender-Bares J., Townsend P.A., Couture J.J., Wang Z., Stefanski A., Messier C., and Reich P.B.. 2021. Remote spectral detection of biodiversity effects on forest biomass. Nature Ecology & Evolution 5: 46-54.](https://drive.google.com/file/d/1oTQ6Y-YDAXHprPeod5kzh1hHYpkBeEYz/view?usp=sharing)  

[Williams L.J., Butler E.E., Cavender‐Bares J., Stefanski A., Rice K.E., Messier C., Paquette A., and Reich P.B. 2021. Enhanced light interception and light use efficiency explain overyielding in young tree communities. Ecology letters 24: 996-1006.](https://drive.google.com/file/d/1DW-qOfKmyb0_joAXMiOsB2_mSCniYQzD/view?usp=sharing)  

### Media