---
title: "Ankom Fiber Analyzer"
date: "`r Sys.Date()`"
output: md_document
author: "Cathleen Lapadat"
---

### Goal

This protocol serves as a guide to use the Ankom Fiber Analyzer.

### Ankom Protocol for the Hobbie Lab

The Ankom Fiber Analyzer utilizes a series of extractions to determine the fiber 
content of a plant sample. Each of the extractions should be done in the order 
of NDF (Neutral Detergent Fiber), ADF (Acid Detergent Fiber), then ADL 
(Acid Determined Lignin). The NDF solution is just soapy water. During NDF, 
the fraction that is washed off contains soluble cell contents like carbohydrates, 
lipids, pectin, starch, soluble proteins and non-protein nitrogen. The fraction 
that is left in the bag contains hemicellulose, proteins bound to the cell walls, 
cellulose, lignin, and recalcitrant materials. ADF solution is a 1.00 Normal 
sulfuric acid and detergent solution. During ADF, hemicellulose and bound proteins 
are washed off. The fraction left behind contains cellulose, lignin, and recalcitrant 
materials. The ADL solution is ultra nasty 72% sulfuric acid. During ADL, 
cellulose is washed off leaving only lignin and recalcitrant materials.  All 
calculations can be found in the Template spreadsheet in the Ankom Data folder 
on the computer in the Hobbie Lab.

### Supplies
All Ankom solutions can be ordered from Ankom:

```
Ankom Technology
140 Turk Hill Park
Fairport, NY 14450
phone: 716-425-3940
fax: 716-425-3941
www.ankom.com
```

### Updated 2/28/2019
- Neutral Detergent solution - catalog # FND20 - 20 L for $95, 20L for $113.
- Acid Detergent 5x solution - catalog # FAD20 - 1 L (dilutes to 5 L) for $80, 20L for $75, 20L for $93.
- 72% Sulfuric acid - catalog # FSA72 - 1 L for $34.
- Filter bags - catalog # F57 – 200 for $240, 200 for $252.

### Steps for sample preparation

1. Grind samples using a 1 mm screen and dry.
2. Label bags with special Ankom marker or permanent Sharpie.
3. Tare Ankom bag and record weight.
4. Weigh out .5 g (± 0.05 g) of sample and record weight. Include a blank bag in 
each run (each batch of 24) for a blank bag correction.
5. Seal the bag closed within 0.5 cm from the open edge using the heat sealer. 
Be sure to seal the blank bag too.
6. Spread sample uniformly inside the filter bag by shaking and lightly flicking 
the bag to eliminate clumping.
7. A maximum of 24 bags may be place in the bag suspender. All nine trays are 
used regardless of the number of bags being processed. Place three bags per tray 
and then stack trays on center post with each level rotated 120 degrees. Each 
tray will sit in the notches of the tray below it. The weight is placed on top 
of the empty 9 th tray to keep the bag suspender submerged.