---
title: "Spectra of Dried Specimen"
date: "`r Sys.Date()`"
output: md_document
author: "Cathleen Lapadat"
---
### Introduction
Documentation of important data files that match with spectra taken in spring 2021. Not all individuals in each file were successfully matched. The live oaks were collected in several different locations (from a live oak phylogeography project) including throughout South United States, Central and South America. There are many copies of one excel file in the Live Oaks\ folder. The matched files are not limited to the files mentioned below. The most recent files were chosen. Also, there are some variations of the sample ID between different types of data e.g. MX-MB3030 and MXMB3030.

### Spectra
##### Files

There are 3 files created on Fulcrum App that document metadata and storage location of the spectra of dried live oaks taken in spring 2021. The README.txt has column definitions. The fulcrum_id in file 1 links to the fulcrum_parent_id in file 2. The files are linked from the shared google drive and are also stored in the University shared drive (Lab-cavender\4_Project_Folders\Live Oaks\Spectra of Dried Specimen\)

File 1: [live_oaks_leaf_spectra.csv](https://drive.google.com/file/d/1d6OAtn-64dOzv6w7fhMUof_7VvqFjh-J/view?usp=sharing)  
File 2: [live_oaks_leaf_spectra_spectral_measurements.csv](https://drive.google.com/file/d/1XIT7dEnRDVNNQvHG5SgdcUTJHV3Syohb/view?usp=sharing)  
File 3: [README.txt](https://drive.google.com/file/d/1rZLfSgHOGfEWay7lIOdNPRKEz9CqndHa/view?usp=sharing)  

### Molecular Data
##### Microsatellite Sequences

File 1: Lab-cavender\4_Project_Folders\Live Oaks\Live oak phylogeography\2009_microsats\11 microsats_Sept10.xls  

**Raw sequences:** Lab-cavender\4_Project_Folders\Live Oaks\Live oak phylogenetics\All Live oaks\Data*  

##### Chloroplast DNA
Path: LAB-cavender\4_Project_Folders\Live Oaks\Live oak phylogeography II\Molecular Data\Cp DNA\  

Note: Path includes few folders containing full sequences.  

### Morphology
Foliar area of leaf scans.

File 1: Lab-cavender\4_Project_Folders\Live Oaks\Live oak phylogeography II\Morphology documentation\Anne's Shape Results\All together\All_Virentes.xlsx  